import Image from 'next/image';
import React, { useEffect } from 'react'
import styles from "../../styles/AdminManage.module.css"
import { useUser } from "@auth0/nextjs-auth0";
import Head from "next/head";
import Router from 'next/router';
import mongoose from 'mongoose';
import Products from "../../models/ProductSchema.js";
import { Typography } from '@mui/material';
import { Box } from '@mui/system';
import AdminAppbar from '../../components/Appbar';



const Profile = ({ allshirts, allhoodies }) => {

    const { user, error, isLoading } = useUser();

    useEffect(() => {

        if (user) {
            if (user.email !== "gyansujan69@gmail.com")
                Router.push("/api/auth/login");
        }
    }, [user]);

    useEffect(() => {
        console.log(allshirts);
        console.log(allhoodies);
    }, [allshirts, allhoodies]);




    return (
        <>
            {user && <Head>
                <title> {user.name.split(" ")[0]} | Cart </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>}



            <Box>

                <AdminAppbar />

            </Box>


        </>
    )
}



export default Profile

export async function getServerSideProps(context) {

    if (!mongoose.connections[0].readyState) {
        await mongoose.connect(process.env.MONGO_URI);
    }


    let allshirts = await Products.find({ category: "tshirt" });
    let allhoodies = await Products.find({ category: "hoodies" });


    // res.status(200).json({ allproducts });
    return {
        // props: { allproducts: JSON.parse(JSON.stringify(allproducts)) }, // will be passed to the page component as props
        props: { allshirts: JSON.parse(JSON.stringify(allshirts)), allhoodies: JSON.parse(JSON.stringify(allhoodies)) }, // will be passed to the page component as props
    }
}