import React, { useState, useEffect } from 'react'
import Image from "next/legacy/image";
import sales from "../public/assets/sale.svg";
import Head from "next/head";
import styles from "../styles/Shoptshirts.module.css"
import { BsFillCartFill, BsFillHeartFill } from "react-icons/bs";
import Link from 'next/link';


const TshirtCard = ({ product }) => {

    const [creds, setcreds] = useState("");

    useEffect(() => {
        const useremail = localStorage.getItem("useremail");
        setcreds(useremail);

    }, []);


    return (
        <>
            <Head>
                <title>ShopCoders | T-Shirts</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <Link href={`/detailed-product/${product.slug}&${creds}`} passHref>




                    <div className={`card ${styles.itemscard_card}`} style={{ width: "18rem" }}>
                        <Image src={product.img} className={`card-img-top ${styles.itemscard_img}`} alt="..." height={300} width={300} />

                        <div className="card-body">

                            <h5 className={`card-title ${styles.itemscard_title}`}>{product.name}</h5>




                            <h5 className={styles.itemcard_price}>$ {product.price}</h5>

                            <BsFillCartFill
                                size={20}
                                style={{ fill: "#C70A80", marginRight: "1rem", cursor: "pointer" }}
                            />

                            <BsFillHeartFill
                                size={20}
                                style={{ fill: "#F24C4C", marginRight: "5px", cursor: "pointer" }}
                            />

                        </div>
                    </div>


                </Link>
            </div>



        </>
    )
}

export default TshirtCard