import React from 'react'
import Image from "next/image";
import sales from "../public/assets/sale.svg";
import Link from 'next/link'
import Head from "next/head";
import styles from "../styles/Shoptshirts.module.css"
import { BsFillCartFill, BsFillHeartFill } from "react-icons/bs";

const TshirtCard = ({ product }) => {
    return (
        <>
            <Head>
                <title>ShopCoders | T-Shirts</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Link href={`/detailed-product/${product.slug}`} passHref>




                <div className={`card ${styles.itemscard_card}`} style={{ width: "18rem" }}>
                    <Image src={product.img} className={`card-img-top ${styles.itemscard_img}`} alt="..." height={300} width={300} />

                    <div className="card-body">

                        <h5 className={`card-title ${styles.itemscard_title}`}>{product.name}</h5>




                        <h5 className={styles.itemcard_price}>$ {product.price}</h5>

                        <BsFillCartFill
                            size={20}
                            style={{ fill: "#C70A80", marginRight: "1rem", cursor: "pointer" }}
                        />

                        <BsFillHeartFill
                            size={20}
                            style={{ fill: "#F24C4C", marginRight: "5px", cursor: "pointer" }}
                        />

                    </div>
                </div>


            </Link>



        </>
    )
}

export default TshirtCard