/* eslint-disable @next/next/no-img-element */
import React from 'react'
import styles from "../../styles/Shoptshirts.module.css"
import Navbar from "../../components/Navbar.jsx"
import Products from "../../models/ProductSchema.js";
import mongoose from 'mongoose'
import Link from 'next/link';
import Image from 'next/legacy/image'
import Head from 'next/head';

const Shoptshirts = ({ allproducts }) => {
    return (
        <>
            <Head>
                <title>ShopCoders | TShirts </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className={styles.shirtpage_main}>
                <div className={styles.shirtpage_main_heading}>
                    <h1>We have all the Ts you&apos;ll ever need</h1>
                    <hr />
                    <div className={`input-group mb-3 ${styles.searchmaindiv}`}>
                        <input type="text" class="form-control" placeholder="Enter product name" aria-label="Recipient's username" aria-describedby="button-addon2" />
                        <button class="btn btn-outline-secondary" type="button" id="button-addon2">Search</button>
                    </div>
                </div>
                <div className={styles.pb_cardsdiv}>
                    {allproducts.map((product, index) => (
                        <div className={styles.pb_cardmain} key={index}>
                            <div className={styles.pb_cardimgdiv}>
                                <Image src={product.img} width={300} height={280} alt=" picture of the products" />
                            </div>
                            <div className={styles.pb_cardtextdiv}>
                                <p>{product.name}</p>
                                <p>⭐⭐⭐⭐⭐</p>
                                <p>$ {product.price}</p>
                                <p>{product.desc}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </>
    )
}

export async function getServerSideProps(context) {
    if (!mongoose.connections[0].readyState) {
        await mongoose.connect(process.env.MONGO_URI);
    }
    const allproducts = await Products.find({ category: "tshirt" });
    return {
        props: { allproducts: JSON.parse(JSON.stringify(allproducts)) },
    }
}

export default Shoptshirts
