
import mongoose from 'mongoose';
import Image from 'next/image';
import React, { useEffect, useState } from 'react'
import Navbar from '../../../components/Navbar.jsx';
import Users from "../../../models/UserSchema.js"
import styles from "../../../styles/Userprofile.module.css"
import { useUser } from "@auth0/nextjs-auth0";
import Link from 'next/link';
import { BsFillCartFill, BsFillHeartFill, BsFillEyeFill } from "react-icons/bs";
import Rating from '@mui/material/Rating';
import Head from "next/head";
import { AiOutlineShoppingCart } from "react-icons/ai";
import profile from "../../../public/assets/profile.svg"



const Profile = ({ singleuser }) => {

    const { user, error, isLoading } = useUser();
    const [profiledetails, setprofiledetails] = useState({ email: "", address: "", state: "", pincode: "", city: "", phone: "" });

    useEffect(() => {

        if (singleuser) {
            setprofiledetails({
                email: singleuser.email,
                address: singleuser.address,
                state: singleuser.state,
                pincode: singleuser.pincode,
                city: singleuser.city,
                phone: singleuser.phone
            })
        }


    }, [])


    return (
        <>
            {user && <Head>
                <title> {user.name.split(" ")[0]} | Cart </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>}


            <div className={styles.cart_mainparent}>

                <Navbar />

                <div className="container" style={{ marginTop: "5rem" }}>
                    <h3 className={styles.cart_cartusername}> Welcome to your profile, {user && user.name.split(" ")[0]} </h3>
                </div>



                <div className={`container ${styles.profileparent}`} style={{ marginTop: "1rem", marginBottom: "5rem" }}>
                    <div className={`row ${styles.profilerow}`}>

                        <div className={`col-lg-6 col-md-12 ${styles.profileimagecol}`}>

                            <Image src={profile} alt="profile" width={500} height={500} className={styles.profileimg} />

                        </div>

                        <div className={`col-lg-6 col-md-12 ${styles.profiledetailscol}`}>

                            {singleuser && <>

                                <input type="text" className='form-control' value={singleuser.email} />
                                <input type="text" className='form-control' />
                                <input type="text" className='form-control' />
                                <input type="text" className='form-control' />
                                <input type="text" className='form-control' />
                                <input type="text" className='form-control' />
                                <input type="text" className='form-control' />
                                <input type="text" className='form-control' />
                                <input type="text" className='form-control' />

                            </>}
                        </div>
                    </div>

                    <br />

                    <Link href="/checkout" passHref >
                        <button className={`btn btn-warning ${styles.cart_checkoutbtn}`}> Update </button>
                    </Link>



                </div>


            </div>



        </>
    )
}

export async function getServerSideProps(context) {

    if (!mongoose.connections[0].readyState) {
        await mongoose.connect(process.env.MONGO_URI);
    }

    let singleproduct = context.query.slug;
    let singleuser = await Users.findOne({ email: context.query.slug });

    return {
        props: {
            singleuser: JSON.parse(JSON.stringify(singleuser)),
        }, // will be passed to the page component as props
    }
}

export default Profile