import React from 'react'
import styles from "../styles/About.module.css"
import Head from "next/head";
import Image from "next/legacy/image"
import aboutus from "../public/assets/aboutus.svg"
import Navbar from '../components/Navbar';
import HomeParticles from '../components/HomeParticles';

const About = () => {
    return (

        <>
            <Head>
                <title>ShopCoders | About us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HomeParticles />

            <Navbar />
            <div className={`container-fluid ${styles.main}`}>

                <div className={styles.aboutimagediv}>
                    <Image src={aboutus} width={550} height={550} alt="abtimg" />
                </div>

                <div className={styles.abouttextdiv}>
                    <h1>Here is all about us !! </h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi cumque placeat voluptatum autem cum iure sapiente aliquam delectus dicta, eius quam, illo, dignissimos et ipsa rerum minus veritatis. Et, amet.</p>
                </div>
            </div>
        </>

    )
}

export default About