import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import sales from "../public/assets/sale.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className={styles.container}>
        <Navbar />
      </div> */}



      <div className="container-fluid" >

        <Navbar />

        <div className={styles.imagediv1}>
          <Image src={sales} width={1500} height={600} />
        </div>


      </div>
    </>
  );
}
