import Head from "next/head";
import Homecontainer from "../components/Homecontainer";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>ShopCoders | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container-fluid">
        <Navbar />
        <Homecontainer />
      </div>
    </>
  );
}
