import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { BsBagCheckFill } from 'react-icons/bs';
import { runFireworks } from '../service/Utils';
import Head from 'next/head';

const PaymentSucess = () => {

    useEffect(() => {
        runFireworks();
    }, []);



    return (

        <>

            <Head>
                <title>Payment success ✅</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className="success-wrapper">
                <div className="success">
                    <p className="icon">
                        <BsBagCheckFill />
                    </p>
                    <h2>Your order is on the way !</h2>
                    <p className="email-msg">Check your email inbox for the receipt.</p>
                    <p className="description">
                        If you have any questions, please email
                        <a className="email" href="mailto:gyansujan69@gmail.com">
                            order@example.com
                        </a>
                    </p>
                    <Link href="/products/shoptshirts" passHref>
                        <button type="button" width="300px" className="btn ps_btn">
                            Continue Shopping
                        </button>
                    </Link>
                </div>
            </div>

        </>
    )
}

export default PaymentSucess